library(CDMConnector)
library(PatientProfiles)
library(IncidencePrevalence)
library(DBI)
library(duckdb)
library(here)
library(usethis)
library(dplyr)
library(dbplyr)

db <- dbConnect(duckdb(), dbdir = eunomia_dir())
cdm <- cdmFromCon(con = db, cdmSchema = "main", writeSchema = "main")
cohorts <- readCohortSet(here("Cohorts"))
cdm <- generateCohortSet(cdm, cohorts, "cohort", TRUE, TRUE)
cohortSet(cdm$cohort)
